state_actions = {
        'state original': handle_state_original,
        'exit exam department': handle_exit_exam_department,
        'engineering exit exam': handle_engineering_exit_exam,
        'applied exit exam': handle_applied_exit_exam,
        'skills': handle_skills,
        'information': handle_information,
        'freshman book language': handle_freshman_book_language,
        'department catagory internship': handle_department_catagory_internship,
        'engineering department internship': handle_engineering_department_internship,
        'applied department internship': handle_applied_department_internship,
        'department catagory instructor': handle_department_catagory_instructor,
        'engineering department instructor': handle_engineering_department_instructor,
        'applied department instructor': handle_applied_department_instructor,
        'department type': handle_department_type,
        'applied': handle_applied,
        'pre': handle_pre,
        'freshman second semester catagory': handle_freshman_second_semester_catagory,
        'engineering': handle_engineering,
        'school': handle_school,
        'department': handle_department,
        'architecture': handle_architecture,
        'chemical': handle_chemical,
        'civil': handle_civil,
        'computer science': handle_computer_science,
        'communication': handle_communication,
        'hydrolics': handle_hydrolics,
        'material': handle_material,
        'mechanical': handle_mechanical,
        'power': handle_power,
        'software': handle_software,
        'architecture junior': handle_architecture_junior,
        'chemical junior': handle_chemical_junior,
        'civil junior': handle_civil_junior,
        'computer science junior': handle_computer_science_junior,
        'communication junior': handle_communication_junior,
        'hydrolics junior': handle_hydrolics_junior,
        'material junior': handle_material_junior,
        'mechanical junior': handle_mechanical_junior,
        'power junior': handle_power_junior,
        'software junior': handle_software_junior,
        'architecture senior': handle_architecture_senior,
        'chemical senior': handle_chemical_senior,
        'civil senior': handle_civil_senior,
        'computer science senior': handle_computer_science_senior,
        'communication senior': handle_communication_senior,
        'hydrolics senior': handle_hydrolics_senior,
        'material senior': handle_material_senior,
        'mechanical senior': handle_mechanical_senior,
        'power senior': handle_power_senior,
        'software senior': handle_software_senior,
        'architecture gc': handle_architecture_gc,
        'chemical gc': handle_chemical_gc,
        'civil gc': handle_civil_gc,
        'computer science gc': handle_computer_science_gc,
        'communication gc': handle_communication_gc,
        'hydrolics gc': handle_hydrolics_gc,
        'material gc': handle_material_gc,
        'mechanical gc': handle_mechanical_gc,
        'power gc': handle_power_gc,
        'software gc': handle_software_gc,
        'freshman first semester': handle_freshman_first_semester,
        'freshman second semester applied': handle_freshman_second_semester_applied,
        'freshman second semester engineering': handle_freshman_second_semester_engineering,
    }